# Generated by Django 4.0.3 on 2022-07-17 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hum', models.IntegerField(default=-1)),
                ('tem', models.IntegerField(default=-1)),
                ('time', models.TimeField(default=datetime.datetime(2022, 7, 17, 16, 16, 36, 841152, tzinfo=utc))),
            ],
        ),
    ]
