# Generated by Django 4.0.3 on 2022-07-17 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_measurement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 17, 16, 18, 46, 190224, tzinfo=utc)),
        ),
    ]
