# Generated by Django 4.0.3 on 2022-07-18 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_measurement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='hum',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 20, 41, 42, 583432, tzinfo=utc)),
        ),
    ]
