# Generated by Django 4.0.3 on 2022-07-20 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_measurement_hum_alter_measurement_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 19, 26, 1, 31183, tzinfo=utc)),
        ),
    ]
