# Generated by Django 4.0.3 on 2022-07-18 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_measurement_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='tem',
            new_name='temp',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 18, 9, 11, 41, 554210, tzinfo=utc)),
        ),
    ]
